spring.application.name=focustrack

spring.datasource.url=jdbc:mysql://localhost:3306/focustrack_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080
